### PR TITLE
capitalization + proper quotation marks

### PR DESCRIPTION
**Pull request by yaskevich**

### CODE REVIEW

**Review by lehkost — CHANGES_REQUESTED** [review]
Okay with the quotation marks (we will have to unify them anyway throughout the corpus), but the capitalisation should not happen, because in the original the word is written with lowercase "к": https://rvb.ru/tolstoy/01text/vol_11/01text/0269.htm (look into source)

**Comment by yaskevich** [comment]
In the source you cite **all** letters are capitalized, which hides real case of letters.
Anyway, according to the rules of Russian orthography, first word of second part of the title of a piece of work which is added via `или` must be capitalized, see: http://new.gramota.ru/spravka/buro/search-answer?s=286933

**Comment by lehkost** [comment]
Yes, I know. But so far we're lower-casing all-caps headlines according to the source file, if possible, and there it is consistently written as is in our TEI, look at ```<meta name="title">```, ```<title>```, etc. – Rules of orthography don't count much in the history of literature. :) We have to follow Tolstoy here, or rather, his editors. Again, we're not making a new edition, we are converting existing digital editions to TEI, giving full credit to our sources.

**Comment by yaskevich** [comment]
But we fix typos, don't we?
By the way, I doubt that there should be quotation marks presented. And historical sources confirm my doubts. It seems that original form is:
>Сочинения графа Л. Н. Толстого. Власть тьмы, или Коготок увяз, всей птичке пропасть. Драма в пяти действиях. Москва, тип. А. И. Мамонтова и К°, 1887. 172 стр.

See: http://old.old.imli.ru/litnasledstvo/Tom%2069-2/vol69-2_7_Булгаков.pdf

**Comment by lehkost** [comment]
Right, but you see that if we start talking about small caps, quotation marks in titles, etc., we lose focus. We're not doing an edition, we take what's digitised (and mark down what edition is the source for the digitisation, e.g., for Tolstoy's plays it's "Собр. соч. в 22 тт." from rvb), everything else is beyond the scope of this project. Our corpus is a downstream corpus and we usually don't meddle with our sources. – But in parallel, we're getting all original scans and at a later stage in the project, we might start comparing selected parts (like title pages) to the original scans. Until then, we should not edit our sources, unless there's a good (consistent) reason.

**Comment by yaskevich** [comment]
Ok, I've got your point about being closer to digital source. But when we do fix typos and when we do not? I ask, because I agree we shouldn't go so deep at this stage to look for printed text, but lower case of second part seems to be just a typo, as an unnecessary hyphen in the epigraph that we corrected.

**Comment by lehkost** [comment]
If we have the **direct print source** for the scan of our digitised version, we can correct things. For example, this commit https://github.com/dracor-org/rusdracor/commit/28e1d33d83a72810d5bef1806443c49f54556ab8 was done because we had access to the [direct print source](https://imwerden.de/pdf/turgenev_pss_sochineniya_tom02_1979_text.pdf#page=287).

But this shouldn't be our focus at all for the time being. At the moment we're growing the corpus as good as we can. Sometime next year, when we finally start to make things look nice on our website, we can take care of consistent quotation marks, consistent dashes, etc., throughout the corpus. But this should be a concerted action following a clear rule set (which we don't have at the moment, because it wasn't our focus). I hope that's a good perspective?

**Comment by yaskevich** [comment]
Yes, very good one!

**Pull request closed without merging**
